apiVersion: v1
kind: Service
metadata:
  name: reactapp
  labels:
    app: reactapp
    tier: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 3000
  selector:
    app: reactapp
    tier: frontend